### ISSUE TITLE
Leave ctrl+d unbound

### ISSUE THREAD

**Issue by thiagomajesk** [ThisIsManta/vscode-cosmic-cursor#2]
Hi!

I like very much what you've done with this extension...
The only thing I'd like to ask is to left <kbd>ctrl+d</kbd> unbound by default.

I think this extension is a great replacement for others like Block Travel only for cursor movement. So, I'd argue that selection/ duplication would be out of the scope.

I see that this extension could easily overlap and thus replace block travel and hungry delete in scope.

**PS.:** I couldn't find a distinction between <kbd>ctrl+shift+right</kbd> & <kbd>ctrl+shift+left</kbd> and the default vs code behavior, am I missing something?

**Comment by ThisIsManta** [comment]
Hi,

Apologies for my extremely late reply!

> I think this extension is a great replacement for others like Block Travel only for cursor movement. So, I'd argue that selection/ duplication would be out of the scope.

Agreed! Soon I will move the commands/keybindings to my other extension: [Sparrow Keys](https://marketplace.visualstudio.com/items?itemName=thisismanta.sparrow-keys).

---

> I couldn't find a distinction between ctrl+shift+right & ctrl+shift+left and the default vs code behavior, am I missing something?

`^` sign below indicates a cursor stop. Notice the following differences:
- `^` within `camelCase`
- `^` after `:`
- `^` inside the empty `()`

|VSCode built-in|This extension|
|---|---|
| "^camelCase^":^ ["^value^",^ ()]^ | "^camel^Case^": ["value^", (^)]^ |
